name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform_module:
    name: "Unit Tests"
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

  terraform_how_to_use:
    name: "Applying in Test"
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN:  ${{ secrets.TF_GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        working-directory: ./how-to-use-this-module
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: ./how-to-use-this-module
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: ./how-to-use-this-module
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        working-directory: ./how-to-use-this-module
        run: terraform plan -no-color

      - name: Terraform - applying in test organization
        id: apply        
        working-directory: ./how-to-use-this-module
        run: terraform apply -auto-approve -no-color
